---
title: Habits
author: John Doe
date: March 22, 2005
output: 
  html_document:
    code_folding: true
runtime: shiny
---

```{r include = F}
library(tidyverse)
library(lubridate)
library(shiny)
source("data/data.R")
```

```{r include = F}
df <- dat[["lap_times"]] %>% 
  inner_join(dat[["races"]] %>%
               select(year, round, circuitName, raceId, circuitId), 
             by = c("raceId"))  %>%
  inner_join(dat[["circuits"]] %>% 
               select(circuitId, country),
             by = c("circuitId")) %>% 
  inner_join(dat[["driver"]] %>% 
               select(driverId, firstName, lastName),
             by = c("driverId")) %>% 
  inner_join(dat[["results"]] %>% 
               select(raceId, driverId, constructorId),
             by = c("raceId", "driverId")) %>% 
  inner_join(dat[["constructors"]] %>% 
               select(constructorId, teamName, nationality),
             by = c("constructorId")) %>% 
  mutate(roundName = paste0("Round ", round, " - ", country)) %>% 
  select(year, circuitName, country, round, roundName, lastName, teamName, lap, position, milliseconds)
```

```{r}
head(df)
```

```{r}
shinyApp(
  ui = fluidPage(
    selectInput("season", "Season:",
                choices = 1996:2019),
    selectizeInput("country","Race:", choices = NULL),
    selectizeInput("teamName","Team:",choices = NULL),
    selectizeInput("lastName","Driver:",choices = NULL),
    plotOutput("phonePlot")
  ),
  server = function(input, output, session) {
    observeEvent(input$season,{
      updateSelectInput(session,"country",
                        choices= df %>% filter(year == input$season) %>% 
                          .$country %>% unique)
    }) 
    observeEvent(input$country,{
      updateSelectInput(session,"teamName",
                        choices= df %>% 
                          filter(year == input$season & country == input$country) %>% 
                          .$teamName %>% unique)
    })
    observeEvent(input$teamName,{
      updateSelectInput(session, "lastName",
                        choices= df %>% 
                          filter(year == input$season & country == input$country & 
                                   teamName == input$teamName) %>%
                          .$lastName %>% unique)
    }) 
    output$phonePlot = renderPlot({df %>% 
        filter(year == input$season &
                 country == input$country &
                 teamName == input$teamName &
                 lastName == input$lastName) %>% 
        ggplot() +
        geom_density(aes(x = milliseconds, y = ..scaled.., fill = lastName), alpha = 1/2) +
        labs(title = "Distribution of Lap Times at 2011 Australian Grand Prix",
             x = "Lap Time (Milliseconds)",
             y = "Percent of Laps",
             fill = "Team") +
        theme(legend.position = "bottom")
    })
  },
  
  options = list(height = 500)
)
```